version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: tallerdocker-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tallerdocker_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "tallerdocker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  servicio-aulas:
    image: dumarmalpica/servicio-aulas:latest   
    container_name: tallerdocker-servicio-aulas
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tallerdocker_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  servicio-prestamos:
    image: dumarmalpica/servicio-prestamos:latest
    container_name: tallerdocker-servicio-prestamos
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tallerdocker_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  servicio-reportes:
    image: dumarmalpica/servicio-reportes:latest
    container_name: tallerdocker-servicio-reportes
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tallerdocker_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
